---
- name: Setup and Deploy Network Scanner Application
  hosts: all
  become: yes
  tasks:

    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install required packages
      apt:
        name: 
          - docker.io
          - docker-compose
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to Docker group (if needed)
      user:
        name: admin
        groups: docker
        append: yes

    - name: Pull latest Docker image
      command: docker pull prathamesh05/network_scanner:latest

    - name: Remove existing container (if running)
      command: docker rm -f network_scanner
      ignore_errors: yes  # Ignore errors if container does not exist

    - name: Run Docker container with privileged mode
      command: >
        docker run --privileged -d --name network_scanner
        -p 5000:5000 prathamesh05/network_scanner:latest

    - name: Verify container is running
      command: docker ps
      register: container_status

    - debug:
        var: container_status.stdout_lines

